export type ArticlePlaceholder = typeof articlePlaceholder;

export const articlePlaceholder = [
  {
    id: "1",
    title: "The Complete Guide to Time Management",
    author: "John Doe",
    authorId: "a1",
    date: new Date("2025-01-10T12:00:00"),
    imageUrl: "https://placehold.co/1280x720?text=Image+Banner",
    content: "This article provides tips on how to efficiently manage your work time...",
    tags: ["time", "management", "work"],
    category: "Career",
    excerpt: "This article provides tips on time management...",
    slug: "the-complete-guide-to-time-management"
  },
  {
    id: "2",
    title: "Healthy Foods to Boost Your Stamina",
    author: "Jane Smith",
    authorId: "a2",
    date: new Date("2025-01-09T09:30:00"),
    imageUrl: "https://placehold.co/1280x720?text=Image+Banner",
    content: "In this article, we discuss several foods that help maintain stamina...",
    tags: ["health", "healthy food", "stamina"],
    category: "Health",
    excerpt: "Foods that help boost your stamina...",
    slug: "healthy-foods-to-boost-your-stamina"
  },
  {
    id: "3",
    title: "Effective Ways to Learn a Foreign Language in the Digital Age",
    author: "Michael Lee",
    authorId: "a3",
    date: new Date("2025-01-08T15:45:00"),
    imageUrl: "https://placehold.co/1280x720?text=Image+Banner",
    content: "Learning a foreign language is easier now thanks to technological advancements. This article offers effective tips...",
    tags: ["foreign language", "learning", "digital"],
    category: "Education",
    excerpt: "Learning a foreign language is easier now with technology...",
    slug: "effective-ways-to-learn-a-foreign-language-in-the-digital-age"
  },
  {
    id: "4",
    title: "10 Best Travel Destinations in Indonesia",
    author: "Rina Wijaya",
    authorId: "a4",
    date: new Date("2025-01-07T10:15:00"),
    imageUrl: "https://placehold.co/1280x720?text=Image+Banner",
    content: "Indonesia has many amazing travel destinations. This article covers the 10 best places to visit...",
    tags: ["travel", "destinations", "Indonesia"],
    category: "Travel",
    excerpt: "This article covers 10 of the best travel destinations in Indonesia...",
    slug: "10-best-travel-destinations-in-indonesia"
  },
  {
    id: "5",
    title: "The Benefits of Investing in the Stock Market",
    author: "Sandy Pratama",
    authorId: "a5",
    date: new Date("2025-01-06T14:00:00"),
    imageUrl: "https://placehold.co/1280x720?text=Image+Banner",
    content: "Investing in the stock market offers great potential returns, but also carries risks...",
    tags: ["investment", "stocks", "finance"],
    category: "Finance",
    excerpt: "Investing in the stock market offers great potential returns...",
    slug: "the-benefits-of-investing-in-the-stock-market"
  },
  {
    id: "6",
    title: "Digital Marketing Strategies for Small Businesses",
    author: "Diana Sari",
    authorId: "a6",
    date: new Date("2025-01-05T11:30:00"),
    imageUrl: "https://placehold.co/1280x720?text=Image+Banner",
    content: "Digital marketing is essential for small businesses to compete in today’s market...",
    tags: ["digital marketing", "small business", "strategies"],
    category: "Business",
    excerpt: "Digital marketing is essential for small businesses to compete...",
    slug: "digital-marketing-strategies-for-small-businesses"
  },
  {
    id: "7",
    title: "How to Manage Stress at Work",
    author: "Tina Hartanto",
    authorId: "a7",
    date: new Date("2025-01-04T13:00:00"),
    imageUrl: "https://placehold.co/1280x720?text=Image+Banner",
    content: "Stress at work is a common issue that can reduce productivity. Here are some solutions...",
    tags: ["stress", "work", "solutions"],
    category: "Career",
    excerpt: "Stress at work can reduce productivity. Here are some ways to manage it...",
    slug: "how-to-manage-stress-at-work"
  },
  {
    id: "8",
    title: "Latest Technologies in the Automotive Industry",
    author: "Budi Santoso",
    authorId: "a8",
    date: new Date("2025-01-03T08:45:00"),
    imageUrl: "https://placehold.co/1280x720?text=Image+Banner",
    content: "The automotive industry continues to evolve with new technologies. This article covers the latest trends...",
    tags: ["automotive", "technology", "trends"],
    category: "Technology",
    excerpt: "The automotive industry continues to evolve with the latest technologies...",
    slug: "latest-technologies-in-the-automotive-industry"
  },
  {
    id: "9",
    title: "The Importance of Financial Education for Kids",
    author: "Fajar Nugroho",
    authorId: "a9",
    date: new Date("2025-01-02T16:00:00"),
    imageUrl: "https://placehold.co/1280x720?text=Image+Banner",
    content: "Financial education is crucial for children so they can learn how to manage money wisely...",
    tags: ["financial education", "kids", "financial literacy"],
    category: "Education",
    excerpt: "Financial education is important for kids to learn how to manage money...",
    slug: "the-importance-of-financial-education-for-kids"
  },
  {
    id: "10",
    title: "How to Build a Personal Finance Plan",
    author: "Agus Rahmat",
    authorId: "a10",
    date: new Date("2025-01-01T09:00:00"),
    imageUrl: "https://placehold.co/1280x720?text=Image+Banner",
    content: "A personal finance plan is essential to help you manage your income, expenses, and savings effectively...",
    tags: ["finance", "planning", "personal finance"],
    category: "Finance",
    excerpt: "Learn how to build a personal finance plan to manage your money effectively...",
    slug: "how-to-build-a-personal-finance-plan"
  },
  {
    id: "11",
    title: "Mastering Time Management for Entrepreneurs",
    author: "Lina Purnama",
    authorId: "a11",
    date: new Date("2025-01-01T08:30:00"),
    imageUrl: "https://placehold.co/1280x720?text=Image+Banner",
    content: "Entrepreneurs face unique challenges when it comes to time management. This guide offers tips and strategies...",
    tags: ["entrepreneurship", "time management", "productivity"],
    category: "Career",
    excerpt: "Master time management to increase productivity as an entrepreneur...",
    slug: "mastering-time-management-for-entrepreneurs"
  },
  {
    id: "12",
    title: "Exploring the Future of Artificial Intelligence",
    author: "Ryan Wijaya",
    authorId: "a12",
    date: new Date("2025-01-01T07:45:00"),
    imageUrl: "https://placehold.co/1280x720?text=Image+Banner",
    content: "Artificial intelligence is rapidly advancing and will change various industries. This article looks at its future impact...",
    tags: ["AI", "technology", "future"],
    category: "Technology",
    excerpt: "Explore the future of AI and how it will revolutionize industries...",
    slug: "exploring-the-future-of-artificial-intelligence"
  },
  {
    id: "13",
    title: "How to Create a Healthy Work-Life Balance",
    author: "Dewi Kumala",
    authorId: "a13",
    date: new Date("2025-01-01T07:00:00"),
    imageUrl: "https://placehold.co/1280x720?text=Image+Banner",
    content: "Finding a work-life balance can be challenging, but it's crucial for your well-being. Learn how to manage your time...",
    tags: ["work-life balance", "health", "career"],
    category: "Health",
    excerpt: "Discover ways to balance work and personal life for a healthier lifestyle...",
    slug: "how-to-create-a-healthy-work-life-balance"
  },
  {
    id: "14",
    title: "Exploring the Top Tourist Spots in Europe",
    author: "Carla Mendez",
    authorId: "a14",
    date: new Date("2024-12-31T16:00:00"),
    imageUrl: "https://placehold.co/1280x720?text=Image+Banner",
    content: "Europe offers some of the most beautiful and historic tourist destinations in the world. This article highlights the top spots...",
    tags: ["travel", "Europe", "tourism"],
    category: "Travel",
    excerpt: "Check out the top tourist destinations in Europe for your next vacation...",
    slug: "exploring-the-top-tourist-spots-in-europe"
  },
  {
    id: "15",
    title: "Understanding Cryptocurrency and Blockchain",
    author: "Rafael Santoso",
    authorId: "a15",
    date: new Date("2024-12-30T11:30:00"),
    imageUrl: "https://placehold.co/1280x720?text=Image+Banner",
    content: "Cryptocurrency and blockchain are revolutionizing the world of finance. This article explains how they work...",
    tags: ["cryptocurrency", "blockchain", "finance"],
    category: "Technology",
    excerpt: "Get an overview of cryptocurrency and blockchain technology...",
    slug: "understanding-cryptocurrency-and-blockchain"
  },
  {
    id: "16",
    title: "The Rise of Remote Work and How to Make It Work for You",
    author: "Nina Wulandari",
    authorId: "a16",
    date: new Date("2024-12-29T14:00:00"),
    imageUrl: "https://placehold.co/1280x720?text=Image+Banner",
    content: "Remote work is becoming increasingly popular. This article discusses how to thrive in a remote work environment...",
    tags: ["remote work", "career", "workplace"],
    category: "Career",
    excerpt: "Learn how to adapt to remote work and improve your productivity...",
    slug: "the-rise-of-remote-work-and-how-to-make-it-work-for-you"
  },
  {
    id: "17",
    title: "Exploring Sustainable Living Practices",
    author: "Ella Cahyani",
    authorId: "a17",
    date: new Date("2024-12-28T12:15:00"),
    imageUrl: "https://placehold.co/1280x720?text=Image+Banner",
    content: "Sustainability is more important than ever. This article explores how you can incorporate sustainable practices into your life...",
    tags: ["sustainability", "environment", "lifestyle"],
    category: "Lifestyle",
    excerpt: "Discover practical ways to live more sustainably and protect the environment...",
    slug: "exploring-sustainable-living-practices"
  },
  {
    id: "18",
    title: "How to Start a Successful Blog in 2025",
    author: "Tomi Laksana",
    authorId: "a18",
    date: new Date("2024-12-27T10:30:00"),
    imageUrl: "https://placehold.co/1280x720?text=Image+Banner",
    content: "Starting a blog can be a fun and rewarding experience. In this article, we guide you through the steps to creating a successful blog...",
    tags: ["blogging", "career", "content creation"],
    category: "Business",
    excerpt: "Learn how to start a successful blog with our step-by-step guide...",
    slug: "how-to-start-a-successful-blog-in-2025"
  }
];
